# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-24 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('matter_id', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=52)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], max_length=1)),
                ('case_list_name', models.CharField(max_length=59)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=52)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], max_length=1)),
                ('client_list_name', models.CharField(max_length=59)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Import_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('ran_by', models.CharField(max_length=39)),
                ('results', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('set_code_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('set_code', models.CharField(max_length=1)),
                ('code', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Timekeeper',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=12)),
                ('middle_ini', models.CharField(blank=True, max_length=2)),
                ('last_name', models.CharField(max_length=16)),
                ('full_name', models.CharField(max_length=55)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climats.Company'),
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climats.Client'),
        ),
        migrations.AddField(
            model_name='case',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climats.Company'),
        ),
    ]
