# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-25 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timekeeper',
            name='default_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climats.Company'),
        ),
    ]
