# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climats', '0002_import_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_log',
            name='ran_by',
            field=models.CharField(max_length=39),
        ),
    ]
