# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('climats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(null=True)),
                ('matter', models.CharField(max_length=10, null=True)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('narrative', models.TextField(blank=True)),
                ('created_date', models.DateField(null=True)),
                ('last_change_date', models.DateField(auto_now=True, null=True)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('exported_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('O', 'Open'), ('R', 'Released'), ('E', 'Exported')], default='O', max_length=1)),
                ('activity_code1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acode1', to='climats.Activity')),
                ('activity_code2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acode2', to='climats.Activity')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='climats.Case')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='climats.Client')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='climats.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='climats.Timekeeper')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_whom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climats.Timekeeper', verbose_name='entering for')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
