# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-24 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20160924_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expthru',
            name='thru_date',
            field=models.DateField(default=datetime.datetime(2016, 9, 24, 16, 7, 32, 727590), verbose_name='Through Date'),
        ),
    ]
