# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-26 17:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20160924_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='expthru',
            name='key_list',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='expthru',
            name='thru_date',
            field=models.DateField(default=datetime.datetime(2016, 9, 26, 17, 11, 13, 793818), verbose_name='Through Date'),
        ),
    ]
