# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 12:39
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20160705_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='client',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='company', chained_model_field='company', null=True, on_delete=django.db.models.deletion.CASCADE, to='climats.Client'),
        ),
    ]
