# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 13:06
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20160802_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='case',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='client', chained_model_field='client', null=True, on_delete=django.db.models.deletion.CASCADE, to='climats.Case'),
        ),
    ]
