# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 07:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20160926_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export_Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('ran_by', models.CharField(max_length=39)),
                ('results', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='expthru',
            name='thru_date',
            field=models.DateField(default=datetime.datetime(2016, 9, 27, 7, 40, 32, 333970), verbose_name='Through Date'),
        ),
    ]
