# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20160802_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='released',
            field=models.BooleanField(default='False'),
        ),
    ]
