# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 22:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20160927_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recent_days',
            field=models.IntegerField(default=15, verbose_name='Days until recent files deleted'),
        ),
        migrations.AlterField(
            model_name='expthru',
            name='thru_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 3, 22, 41, 30, 620648), verbose_name='Through Date'),
        ),
    ]
