# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 22:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20161003_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mre_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 10, 3, 22, 42, 35, 914858, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expthru',
            name='thru_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 3, 22, 42, 23, 746649), verbose_name='Through Date'),
        ),
    ]
