# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 22:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20161003_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expthru',
            name='thru_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 3, 22, 43, 10, 590103), verbose_name='Through Date'),
        ),
    ]
