# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 23:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_auto_20161003_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expthru',
            name='thru_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 3, 23, 42, 24, 794573), verbose_name='Through Date'),
        ),
    ]
