# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 00:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climats', '0001_initial'),
        ('entries', '0010_auto_20161003_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matter_use',
            fields=[
                ('worker_case', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('last_used', models.DateField(default=datetime.datetime(2016, 10, 4, 0, 15, 44, 839283))),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climats.Case')),
                ('timekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climats.Timekeeper')),
            ],
        ),
        migrations.AlterField(
            model_name='expthru',
            name='thru_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 4, 0, 15, 44, 839862), verbose_name='Through Date'),
        ),
    ]
