# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_auto_20160804_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='exported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
