# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-04 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_auto_20160804_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='matter',
        ),
    ]
