# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 13:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0017_auto_20161004_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='recent_files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.Matter_use'),
        ),
        migrations.AlterField(
            model_name='expthru',
            name='thru_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 4, 13, 50, 58, 615010), verbose_name='Through Date'),
        ),
    ]
