# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 21:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0018_auto_20161004_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='case',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='client', chained_model_field='client', null=True, on_delete=django.db.models.deletion.CASCADE, to='climats.Case'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='recent_files',
            field=models.ForeignKey(blank=True, help_text='Select to fill in company, client, and case', null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.Matter_use'),
        ),
        migrations.AlterField(
            model_name='expthru',
            name='thru_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 6, 21, 20, 59, 230659), verbose_name='Through Date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='recent_days',
            field=models.IntegerField(default=15, help_text='until files deleted from recent files list.', verbose_name='Days'),
        ),
    ]
