# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0019_auto_20161006_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='client',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='company', chained_model_field='company', null=True, on_delete=django.db.models.deletion.CASCADE, to='climats.Client'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='recent_files',
            field=models.ForeignKey(blank=True, help_text='Select a recent file to override company, client, and case', null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.Matter_use'),
        ),
        migrations.AlterField(
            model_name='expthru',
            name='thru_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 10, 14, 58, 54, 166993), verbose_name='Through Date'),
        ),
    ]
