# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-10 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0020_auto_20161010_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='case',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='client', chained_model_field='client', null=True, on_delete=django.db.models.deletion.CASCADE, to='climats.Case'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climats.Company'),
        ),
        migrations.AlterField(
            model_name='expthru',
            name='thru_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 10, 15, 7, 11, 483795), verbose_name='Through Date'),
        ),
    ]
