# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-19 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0021_auto_20161010_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='company',
            field=models.ForeignKey(default='CH', on_delete=django.db.models.deletion.CASCADE, to='climats.Company'),
        ),
        migrations.AlterField(
            model_name='expthru',
            name='thru_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 19, 21, 21, 15, 450951), verbose_name='Through Date'),
        ),
    ]
